# Generated by Django 5.0.2 on 2024-03-20 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "carts",
            "0002_alter_cart_options_alter_cart_created_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Cart"},
        ),
    ]
