# Generated by Django 5.0.2 on 2024-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "goods",
            "0002_alter_categories_options_alter_categories_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
